"""Creating todos table

Revision ID: 30383fbd4ed1
Revises: 
Create Date: 2024-06-06 14:14:26.329115

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '30383fbd4ed1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    #Inserting record into the table for testing
    op.execute(
        """
        INSERT INTO todos (id, title, description, creation_date, is_finished)
        VALUES (13, 'Sample Todo', 'This is a sample task description', '{}', False)
        """.format(datetime.now())
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
