"""Adding test column

Revision ID: 6d7b342e1214
Revises: 30383fbd4ed1
Create Date: 2024-06-06 14:19:54.464023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7b342e1214'
down_revision = '30383fbd4ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('test', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'test')
    # ### end Alembic commands ###
