"""Adding foreign key to the todos table

Revision ID: 2924e0167553
Revises: e198bf6cbb54
Create Date: 2024-08-23 14:54:59.882689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2924e0167553'
down_revision = 'e198bf6cbb54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(constraint_name='todos_user_id_fkey', source_table='todos', referent_table='users', local_cols=['user_id'], remote_cols=['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(constraint_name='todos_user_id_fkey', table_name='todos', type_='foreignkey')
    op.drop_column('todos', 'user_id')
    # ### end Alembic commands ###
