"""Changing column definition for the password field.

Revision ID: e198bf6cbb54
Revises: bd5cbf161eca
Create Date: 2024-08-23 12:34:20.944191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e198bf6cbb54'
down_revision = 'bd5cbf161eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE users ALTER COLUMN password TYPE BYTEA USING password::bytea')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.LargeBinary(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE users ALTER COLUMN password TYPE VARCHAR(255)')
    op.alter_column('users', 'password',
               existing_type=sa.LargeBinary(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
